### ISSUE TITLE
Unable to map literal exception (Infinity value mapping)

### ISSUE THREAD

**Issue by grigoart** [kbss-cvut/jopa#108]
After upgrading Jopa from [0.17.2](https://github.com/kbss-cvut/jopa/releases/tag/v0.17.2) to [0.18.3](https://github.com/kbss-cvut/jopa/releases/tag/v0.18.3) (or even [0.18.4](https://github.com/kbss-cvut/jopa/releases/tag/v0.18.4)) without changing any code or configuration, a problem occurs during ORM. To be more precise the exception occurs when mapping `"INF"^^<http://www.w3.org/2001/XMLSchema#double>` to `java.lang.Double`.
```
Caused by: cz.cvut.kbss.jopa.exceptions.StorageAccessException: cz.cvut.kbss.ontodriver.sesame.exceptions.SesameDriverException: cz.cvut.kbss.jopa.datatype.exception.DatatypeMappingException: Unable to map literal "INF"^^<http://www.w3.org/2001/XMLSchema#double>
	at cz.cvut.kbss.jopa.oom.EntityInstanceLoader.loadInstance(EntityInstanceLoader.java:97) ~[jopa-impl-0.18.4.jar:na]
	at cz.cvut.kbss.jopa.oom.DefaultInstanceLoader.loadEntity(DefaultInstanceLoader.java:32) ~[jopa-impl-0.18.4.jar:na]
	at cz.cvut.kbss.jopa.oom.ObjectOntologyMapperImpl.loadEntityInternal(ObjectOntologyMapperImpl.java:109) ~[jopa-impl-0.18.4.jar:na]
	at cz.cvut.kbss.jopa.oom.ObjectOntologyMapperImpl.loadEntity(ObjectOntologyMapperImpl.java:100) ~[jopa-impl-0.18.4.jar:na]
	at cz.cvut.kbss.jopa.sessions.ConnectionWrapper.find(ConnectionWrapper.java:54) ~[jopa-impl-0.18.4.jar:na]
	at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.readObjectInternal(UnitOfWorkImpl.java:154) ~[jopa-impl-0.18.4.jar:na]
	at cz.cvut.kbss.jopa.sessions.UnitOfWorkImpl.readObject(UnitOfWorkImpl.java:143) ~[jopa-impl-0.18.4.jar:na]
	at cz.cvut.kbss.jopa.model.EntityManagerImpl.find(EntityManagerImpl.java:288) ~[jopa-impl-0.18.4.jar:na]
	at cz.cvut.kbss.jopa.model.EntityManagerImpl.find(EntityManagerImpl.java:273) ~[jopa-impl-0.18.4.jar:na]
	at com.github.ledsoft.jopa.spring.transaction.SingleOperationEntityManagerProxy.find(SingleOperationEntityManagerProxy.java:62) ~[jopa-spring-transaction-0.1.1.jar:na]
	at com.github.ledsoft.jopa.spring.transaction.DelegatingEntityManager.find(DelegatingEntityManager.java:74) ~[jopa-spring-transaction-0.1.1.jar:na]
	at com.csat.support.monitor.persistence.dao.BaseDao.find(BaseDao.java:59) ~[classes/:na]
	at com.csat.support.monitor.persistence.dao.BaseDao$$FastClassBySpringCGLIB$$966d1205.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.9.jar:5.3.9]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.9.jar:5.3.9]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.9.jar:5.3.9]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.9.jar:5.3.9]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.9.jar:5.3.9]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.9.jar:5.3.9]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.9.jar:5.3.9]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.9.jar:5.3.9]
	at com.csat.support.monitor.persistence.dao.InfTestDao$$EnhancerBySpringCGLIB$$b2c997ff.find(<generated>) ~[classes/:na]
	at com.csat.support.monitor.MonitorApplication.lambda$0(MonitorApplication.java:40) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) ~[spring-boot-2.5.4.jar:2.5.4]
	... 5 common frames omitted
Caused by: cz.cvut.kbss.ontodriver.sesame.exceptions.SesameDriverException: cz.cvut.kbss.jopa.datatype.exception.DatatypeMappingException: Unable to map literal "INF"^^<http://www.w3.org/2001/XMLSchema#double>
	at cz.cvut.kbss.ontodriver.sesame.SesameConnection.find(SesameConnection.java:178) ~[ontodriver-sesame-0.18.4.jar:na]
	at cz.cvut.kbss.jopa.oom.EntityInstanceLoader.loadInstance(EntityInstanceLoader.java:94) ~[jopa-impl-0.18.4.jar:na]
	... 28 common frames omitted
Caused by: cz.cvut.kbss.jopa.datatype.exception.DatatypeMappingException: Unable to map literal "INF"^^<http://www.w3.org/2001/XMLSchema#double>
	at cz.cvut.kbss.jopa.datatype.xsd.XsdDatatypeMapper.map(XsdDatatypeMapper.java:99) ~[datatype-0.18.4.jar:na]
	at cz.cvut.kbss.ontodriver.sesame.util.SesameUtils.getLiteralValue(SesameUtils.java:62) ~[ontodriver-sesame-0.18.4.jar:na]
	at cz.cvut.kbss.ontodriver.sesame.util.AxiomBuilder.createValue(AxiomBuilder.java:78) ~[ontodriver-sesame-0.18.4.jar:na]
	at cz.cvut.kbss.ontodriver.sesame.util.AxiomBuilder.resolveValue(AxiomBuilder.java:49) ~[ontodriver-sesame-0.18.4.jar:na]
	at cz.cvut.kbss.ontodriver.sesame.util.AxiomBuilder.statementToAxiom(AxiomBuilder.java:53) ~[ontodriver-sesame-0.18.4.jar:na]
	at cz.cvut.kbss.ontodriver.sesame.util.AxiomBuilder.statementToAxiom(AxiomBuilder.java:42) ~[ontodriver-sesame-0.18.4.jar:na]
	at cz.cvut.kbss.ontodriver.sesame.StatementLoader.loadAll(StatementLoader.java:105) ~[ontodriver-sesame-0.18.4.jar:na]
	at cz.cvut.kbss.ontodriver.sesame.StatementLoader.loadAxioms(StatementLoader.java:69) ~[ontodriver-sesame-0.18.4.jar:na]
	at cz.cvut.kbss.ontodriver.sesame.AxiomLoader.findStatements(AxiomLoader.java:65) ~[ontodriver-sesame-0.18.4.jar:na]
	at cz.cvut.kbss.ontodriver.sesame.AxiomLoader.loadAxioms(AxiomLoader.java:53) ~[ontodriver-sesame-0.18.4.jar:na]
	at cz.cvut.kbss.ontodriver.sesame.SesameAdapter.find(SesameAdapter.java:179) ~[ontodriver-sesame-0.18.4.jar:na]
	at cz.cvut.kbss.ontodriver.sesame.SesameConnection.find(SesameConnection.java:176) ~[ontodriver-sesame-0.18.4.jar:na]
	... 29 common frames omitted
Caused by: java.lang.NumberFormatException: For input string: "INF"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[na:na]
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[na:na]
	at java.base/java.lang.Double.parseDouble(Double.java:651) ~[na:na]
	at cz.cvut.kbss.jopa.datatype.xsd.XsdDatatypeMapper.map(XsdDatatypeMapper.java:72) ~[datatype-0.18.4.jar:na]
	... 40 common frames omitted
```

Code to reproduce: [kbss-cvut/csat-planning/tree/issue-65/src/main/java/com/csat/support/monitor/MonitorApplication.java#L50](https://github.com/kbss-cvut/csat-planning/blob/fb3cad57d087cdc4f5b7d442f17d0a416c944a8d/src/main/java/com/csat/support/monitor/MonitorApplication.java#L50) (see `CommandLineRunner runner` method, the problem occurs when loading entity from the repository with clean persistence context, i.e. after the second run of the provided code).

**Comment by ledsoft** [comment]
Fixed in 0.18.5.
