### ISSUE TITLE
`EntityManager.isInferred` throws NullPointerException when LazyLoadingProxy is passed to it

### ISSUE THREAD

**Issue by ledsoft** [kbss-cvut/jopa#252]
When I want to check whether a value is inferred, but the value is a `EntityLazyLoadingProxy` instance, it causes a NPX, because the value is translated to `NullValue`. See the following stacktrace segment:

```
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "value" is null
    at cz.cvut.kbss.ontodriver.rdf4j.util.Rdf4jUtils.createLiteral(Rdf4jUtils.java:142)
    at cz.cvut.kbss.ontodriver.rdf4j.Rdf4jAdapter.axiomObjectToRdf4jValue(Rdf4jAdapter.java:181)
    at cz.cvut.kbss.ontodriver.rdf4j.Rdf4jAdapter.isInferred(Rdf4jAdapter.java:188)
    at cz.cvut.kbss.ontodriver.rdf4j.Rdf4jConnection.isInferred(Rdf4jConnection.java:181)
    at cz.cvut.kbss.jopa.oom.ObjectOntologyMapperImpl.lambda$isInferred$0(ObjectOntologyMapperImpl.java:388)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
    at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
    at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:657)
    at cz.cvut.kbss.jopa.oom.ObjectOntologyMapperImpl.isInferred(ObjectOntologyMapperImpl.java:392)
    at cz.cvut.kbss.jopa.sessions.ConnectionWrapper.isInferred(ConnectionWrapper.java:97)
    at cz.cvut.kbss.jopa.sessions.AbstractUnitOfWork.isInferred(AbstractUnitOfWork.java:876)
    at cz.cvut.kbss.jopa.model.EntityManagerImpl.isInferred(EntityManagerImpl.java:544)
```

**Comment by ledsoft** [comment]
Note that it seems to happen only for singular values (`EntityLazyLoadingProxy`), not for collection proxies.
